#
# GemsEconomy Main Configuration file.
# Developer(s): [Xanium, Nailm]

storage: mysql
vault: true
debug: false
transaction_log: true
mysql:
  database: bungeecord
  prefix: gemseconomy
  host: localhost
  port: 3306
  username: minecraft
  password: ''
cheque:
  enabled: false
  material: PAPER
  name: '&a支票'
  lore:
    - '&7价值: {value}.'
    - '&7&o发行人 {account}'
messages:
  help:
    eco_command:
      - '&8▸ &a/eco give <user> <amount> [currency] &8- &7Give a player an amount of a currency.'
      - '&8▸ &a/eco take <user> <amount> [currency] &8- &7Take an amount of a currency from a player.'
      - '&8▸ &a/eco set <user> <amount> [currency] &8- &7Set a players amount of a currency.'
    exchange_command:
      - '&8▸ &a/exchange <account> <currency_to_exchange> <amount> <currency_to_receive> <amount> &8- &7Exchange between currencies with a custom rate for an account.'
      - '&8▸ &a/exchange <currency_to_exchange> <amount> <currency_to_receive> <amount> &8- &7Exchange between currencies with a custom rate.'
    cheque_command:
      - '&8▸ &a/cheque write <amount> [currency] &8- &7Write a cheque with a specified amount and currency.'
      - '&8▸ &a/cheque redeem &8- &7Redeem the cheque.'
    currency_command:
      - '&8▸ &a/currency create <singular> <plural> &8- &7Create a currency.'
      - '&8▸ &a/currency delete <plural> &8- &7Delete a currency.'
      - '&8▸ &a/currency view <plural> &8- &7View information about a currency.'
      - '&8▸ &a/currency list &8- &7List of currencies.'
      - '&8▸ &a/currency color <plural> <color> &8- &7Select a color for a currency.'
      - '&8▸ &a/currency symbol <plural> <char|remove> &8- &7Select a symbol for a currency or remove it.'
      - '&8▸ &a/currency default <plural> &8- &7Set a currency as default.'
      - '&8▸ &a/currency setrate <plural> <amount> &8- &7Sets the currency''s exchange rate.'
      - '&8▸ &a/currency payable <plural> &8- &7Set a currency payable or not.'
      - '&8▸ &a/currency decimals <plural> &8- &7Enable decimals for a currency.'
      - '&8▸ &a/currency maxbal <plural> <amount> &8- &7Set the maximum balance for a currency.'
      - '&8▸ &a/currency startbal <plural> <amount> &8- &7Set the starting balance for a currency.'
      - '&8▸ &a/currency convert <method> &8- &7Convert storage method. WARN: Take backups first and make sure the storage you are switching to is empty!'
      - '&8▸ &a/currency backend <method> &8- &7Switch backend. This does not convert.'
