name: GemsEconomy
main: me.xanium.gemseconomy.GemsEconomy
version: ${version}
author: Xanium
description: A multi-currency economy plugin for spigot servers!
website: https://www.spigotmc.org/resources/gemseconomy.19655/
load: STARTUP
api-version: 1.15
loadbefore:
  - ItemFrameShops
depend:
  - CommandAPI
softdepend:
  - Vault
  - NBTAPI
commands:
  balance:
    description: Shows your balances
    usage: /balance (account)
    aliases: [bal, money]
  baltop:
    description: Shows the top balances of the server
    usage: /baltop (currency) (page)
  currency:
    description: Manage the currencies.
    usage: /currency
  economy:
    description: Give, set or take currency.
    usage: /eco <set|take|give> <account> <amount> (currency)
    aliases: [eco]
  pay:
    description: Pays another account
    usage: /pay <account> <amount> (currency)
  cheque:
    usage: /cheque
    description: Write or Redeem a cheque.
  exchange:
    usage: /exchange
    description: Exchange currencies.
