name: GemsEconomy
main: me.xanium.gemseconomy.GemsEconomy
version: ${version}
author: Xanium
description: A multi-currency economy plugin for spigot servers!
website: https://www.spigotmc.org/resources/gemseconomy.19655/
load: STARTUP
api-version: 1.17
loadbefore:
  - ItemFrameShops
depend:
  - CommandAPI
softdepend:
  - Vault
  - NBTAPI